//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsctDecompile.commandtable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsctDecompile.commandtable.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create CodeDOM provider for language {0}..
        /// </summary>
        internal static string CantCreateCodeDOM {
            get {
                return ResourceManager.GetString("CantCreateCodeDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -clean        Clean build (deprecated).
        /// </summary>
        internal static string CmdHelp_Clean {
            get {
                return ResourceManager.GetString("CmdHelp_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line parameter &apos;{0}&apos; can be specified only once..
        /// </summary>
        internal static string CmdLineError_DuplicatedParam {
            get {
                return ResourceManager.GetString("CmdLineError_DuplicatedParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code page specified in -L: {0}.
        /// </summary>
        internal static string CmdLineError_InvalidCodepage {
            get {
                return ResourceManager.GetString("CmdLineError_InvalidCodepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid culture specified in -L: {0}.
        /// </summary>
        internal static string CmdLineError_InvalidCulture {
            get {
                return ResourceManager.GetString("CmdLineError_InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data for parameter &apos;{0}&apos;..
        /// </summary>
        internal static string CmdLineError_MissingParamData {
            get {
                return ResourceManager.GetString("CmdLineError_MissingParamData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file name provided for code file to emit..
        /// </summary>
        internal static string CmdLineError_NoCodeFile {
            get {
                return ResourceManager.GetString("CmdLineError_NoCodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No namespace provided for code file to emit..
        /// </summary>
        internal static string CmdLineError_NoNamespace {
            get {
                return ResourceManager.GetString("CmdLineError_NoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source file specified.
        /// </summary>
        internal static string CmdLineError_NoSource {
            get {
                return ResourceManager.GetString("CmdLineError_NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter &apos;{0}&apos;: already have input ({1}) and output ({2})..
        /// </summary>
        internal static string CmdLineError_TooManyInput {
            get {
                return ResourceManager.GetString("CmdLineError_TooManyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command line parameter &apos;{0}&apos;.
        /// </summary>
        internal static string CmdLineError_UnknownParam {
            get {
                return ResourceManager.GetString("CmdLineError_UnknownParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -D            Specify any additional preprocessor defines..
        /// </summary>
        internal static string CmdLineHelp_D {
            get {
                return ResourceManager.GetString("CmdLineHelp_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -EF:&lt;value&gt;   Name of the file to emit (required if -EL is provided).
        /// </summary>
        internal static string CmdLineHelp_EF {
            get {
                return ResourceManager.GetString("CmdLineHelp_EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -EH:&lt;value&gt;   Emit C++ header file for command items.
        /// </summary>
        internal static string CmdLineHelp_EH {
            get {
                return ResourceManager.GetString("CmdLineHelp_EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -EL:&lt;value&gt;   Programming language to use to emit a code file for command items [C#|C++|VB].
        /// </summary>
        internal static string CmdLineHelp_EL {
            get {
                return ResourceManager.GetString("CmdLineHelp_EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -EN:&lt;value&gt;   Namespace used for the emitted code (required if -EL is provided).
        /// </summary>
        internal static string CmdLineHelp_EN {
            get {
                return ResourceManager.GetString("CmdLineHelp_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -?            Display this help.
        /// </summary>
        internal static string CmdLineHelp_Help {
            get {
                return ResourceManager.GetString("CmdLineHelp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -I            Indicate what additional include path to send the preprocessor.
        /// </summary>
        internal static string CmdLineHelp_I {
            get {
                return ResourceManager.GetString("CmdLineHelp_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -L            Specify the language to use when selecting strings.
        /// </summary>
        internal static string CmdLineHelp_L {
            get {
                return ResourceManager.GetString("CmdLineHelp_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -nologo       Do not display the copyright message.
        /// </summary>
        internal static string CmdLineHelp_N {
            get {
                return ResourceManager.GetString("CmdLineHelp_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vsct &lt;infile&gt; [&lt;outfile&gt;] [&lt;parameter&gt;]*
        ///Where &lt;parameter&gt; is one of the following:.
        /// </summary>
        internal static string CmdLineHelp_Syntax {
            get {
                return ResourceManager.GetString("CmdLineHelp_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -v            Verbose output.
        /// </summary>
        internal static string CmdLineHelp_V {
            get {
                return ResourceManager.GetString("CmdLineHelp_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} will not be generated..
        /// </summary>
        internal static string CodeFileNotGenerated {
            get {
                return ResourceManager.GetString("CodeFileNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft (R) Visual Studio (R) Command Table Compiler Version {0}.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile of a binary command table requires that a symbols exist.  Either &apos;{0}&apos; must contain symbols\nor either &apos;{1}&apos; or &apos;{2}&apos; must exist and contain symbols..
        /// </summary>
        internal static string ErrDecompileWithoutSymbols {
            get {
                return ResourceManager.GetString("ErrDecompileWithoutSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Source file specified..
        /// </summary>
        internal static string ErrNoSourceFile {
            get {
                return ResourceManager.GetString("ErrNoSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string ErrorKindError {
            get {
                return ResourceManager.GetString("ErrorKindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        internal static string ErrorKindWarning {
            get {
                return ResourceManager.GetString("ErrorKindWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file not found..
        /// </summary>
        internal static string ErrSourceNotFound {
            get {
                return ResourceManager.GetString("ErrSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New dependency: {0}.
        /// </summary>
        internal static string NewDependencyMessage {
            get {
                return ResourceManager.GetString("NewDependencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing symbols for &quot;{0}&quot; into target &quot;{1}&quot;..
        /// </summary>
        internal static string ProcessingSymbolsToTarget {
            get {
                return ResourceManager.GetString("ProcessingSymbolsToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSCT: errors   = {0}.
        /// </summary>
        internal static string TotalErrorsSummary {
            get {
                return ResourceManager.GetString("TotalErrorsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSCT: warnings = {0}.
        /// </summary>
        internal static string TotalWarningsSummary {
            get {
                return ResourceManager.GetString("TotalWarningsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSCT{0}.
        /// </summary>
        internal static string VSCTErrorCodeFormat {
            get {
                return ResourceManager.GetString("VSCTErrorCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1},{2}): {3} {4}: {5}.
        /// </summary>
        internal static string VSCTLongErrorFormat {
            get {
                return ResourceManager.GetString("VSCTLongErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSCT.exe : {0} {1}: {2}.
        /// </summary>
        internal static string VSCTShortErrorFormat {
            get {
                return ResourceManager.GetString("VSCTShortErrorFormat", resourceCulture);
            }
        }
    }
}
